# Generated by Django 5.0.3 on 2024-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informasi',
            options={'verbose_name_plural': '2. Informasi'},
        ),
        migrations.AlterModelOptions(
            name='katagori',
            options={'verbose_name_plural': '1. Katagori'},
        ),
        migrations.AlterField(
            model_name='informasi',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='berita'),
        ),
    ]
