# Generated by Django 5.0.3 on 2024-05-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_informasi_usia_artikel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informasi',
            options={'verbose_name_plural': '3. Informasi'},
        ),
    ]
