# Generated by Django 5.0.3 on 2024-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_alter_artikel_options_alter_artikel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pengguna'),
        ),
    ]
