# Generated by Django 5.0.3 on 2024-05-17 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_alter_informasi_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
