# Generated by Django 5.0.3 on 2024-03-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_alter_datapasien_ruangan_rumahsakit_golongan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapasien',
            options={'verbose_name_plural': 'Biodata'},
        ),
    ]
